### ISSUE TITLE
Todo lists

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/saas-stripe#1]
- [x] Add a collection for todo lists (just lists, not items)
- [x] Add a method for inserting todo lists on the server
- [x] Add a method for deleting todo lists on the server
- [x] Add an event for deleting todo lsits on the client
- [x] Add an event for inserting todo lists on the client
- [x] Update method for inserting todo lists on the server to include quota validation against plan limits
